config/routes.rb
Rails.application.routes.draw do
  # get 'tasks', to: 'tasks#index'
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/new', to: 'tasks#new', as: :new_task
  # get 'tasks/:id', to: 'tasks#show', as: :task
  # get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch 'tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy'

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
# TaskController
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def show
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area :details, class: 'form-control' %>
  </div>

  <% unless f.object.new_record? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :completed %> Completed
      </label>
    </div>
  <% end %>
  <%= f.submit class: 'btn btn-primary mt-3' %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container mt-5">
  <h1>Edit task</h1>

  <%= render "form", task: @task %>

  <hr>
  <%= link_to tasks_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container mt-5">
  <h1>My tasks</h1>

  <ul id="tasks">
    <% @tasks.each do |task| %>
      <li>
        <% if task.completed? %>
          <i class="fa-regular fa-square-check"></i>
        <% else %>
          <i class="fa-regular fa-square"></i>
        <% end %>
        <%= link_to task.title, task_path(task.id) %>
        <%= link_to task_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
      </li>
    <% end %>
  </ul>

  <hr>

  <%= link_to new_task_path do %>
    <i class="fa-solid fa-plus"></i> Add a new task
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container mt-5">
  <h1>New task</h1>

  <%= render "form", task: @task %>

  <hr>
  <%= link_to tasks_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1><%= @task.title %></h1>
    <%= link_to edit_task_path(@task.id), class: 'btn btn-light btn-sm border' do %>
      <i class="fa fa-pencil"></i> Edit this task
    <% end %>
  </div>


  <p class="well"><%= @task.details %></p>

  <% if @task.completed %>
    <i class="fa fa-check-square-o"></i> This task is completed
  <% else %>
    <i class="fa fa-square-o"></i> This task is not completed yet
  <% end %>

  <hr>
  <%= link_to tasks_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
</div>